apiVersion: v1
kind: Service
metadata:
  name: order-api
spec:
  selector:
    app.kubernetes.io/name: order-api
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order-api
    spec:
      containers:
        - name: api
          image: opsproof/order-api:v1
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres@postgres:5432/opsproof
            - name: ORDER_STORAGE_MODE
              value: customer
            - name: OTEL_SERVICE_NAME
              value: opsproof-order-api
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://k8s-monitoring-app.opsproof-observability.svc.cluster.local:4317
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 12
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            periodSeconds: 3
